# Generated by Django 2.2 on 2023-01-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={},
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
